import { Product } from "../types/product.types";

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "prod-5228",
    code: "5228",
    name: "CAMISETA ESQUELETO // SAVAGE IRON",
    subtitle: "Corte Boxfit • Algodón Pesado 260 GSM • Lavado Mineral Ácido",
    slug: "5228-camiseta-esqueleto-savage-iron",
    gender: "him",
    price: 119900,
    compareAtPrice: 145000,
    currency: "COP",
    images: [
      "/products/tank-esquelto.jpg",
      "/products/oversize-metal.jpg",
    ],
    swatches: [
      { name: "Negro Mineral Lavado", colorCode: "#242426" },
      { name: "Gris Pizarra", colorCode: "#55555c" },
      { name: "Hueso Vintage", colorCode: "#dedacf" },
    ],
    variants: [
      { id: "5228-s", name: "S", stock: 3, sku: "VF-5228-S" },
      { id: "5228-m", name: "M", stock: 4, sku: "VF-5228-M" },
      { id: "5228-l", name: "L", stock: 2, sku: "VF-5228-L" },
      { id: "5228-xl", name: "XL", stock: 3, sku: "VF-5228-XL" },
      { id: "5228-xxl", name: "XXL", stock: 1, sku: "VF-5228-XXL" },
    ],
    tag: "NUEVO DROP",
    description:
      "Diseñada específicamente para entrenamientos de máxima intensidad. La silueta muscular con sisa amplia acentúa el tren superior y la amplitud de los dorsales mientras permite un rango completo de movimiento en presses y jalones.",
    specifications: {
      gramaje: "260 GSM (Algodón Grueso de Alta Densidad)",
      composicion: "100% Algodón Peinado de Fibra Larga",
      corte: "Boxfit Muscular con Sisas Caídas",
      cuello: "Cuello redondo acanalado grueso",
      cuidados: "Lavar al revés con agua fría • Secar a la sombra • No usar secadora",
    },
    features: [
      "Serigrafía en alto relieve metálico 'VITAL FIT' en el pecho",
      "Ilustración trasera con silueta anatómica de culturismo en alta definición",
      "Tratamiento de lavado ácido que hace cada prenda única en su textura",
      "Costuras reforzadas con doble pespunte para resistir tirones de entrenamiento",
    ],
    sizeGuide: [
      { size: "S", chest: "108 cm", length: "72 cm", shoulders: "48 cm" },
      { size: "M", chest: "114 cm", length: "74 cm", shoulders: "50 cm" },
      { size: "L", chest: "120 cm", length: "76 cm", shoulders: "52 cm" },
      { size: "XL", chest: "126 cm", length: "78 cm", shoulders: "54 cm" },
      { size: "XXL", chest: "132 cm", length: "80 cm", shoulders: "56 cm" },
    ],
    vitalFitPerk: "Desbloquea 30 días VIP en la App VitalFit con la rutina especializada 'Dorsales de Acero'.",
  },
  {
    id: "prod-2108",
    code: "2108",
    name: "CAMISETA OVERSIZE // METAL ANATOMY",
    subtitle: "Drop Shoulder • Heavyweight 280 GSM • Estampado Híbrido Plata/Rojo",
    slug: "2108-camiseta-oversize-metal-anatomy",
    gender: "him",
    price: 139900,
    compareAtPrice: 165000,
    currency: "COP",
    images: [
      "/products/oversize-metal.jpg",
      "/products/tank-esquelto.jpg",
    ],
    swatches: [
      { name: "Negro Ácido / Rojo Cromo", colorCode: "#151515" },
      { name: "Gris Hierro", colorCode: "#3b3b3b" },
      { name: "Blanco Fantasma", colorCode: "#f3f3f3" },
    ],
    variants: [
      { id: "2108-s", name: "S", stock: 5, sku: "VF-2108-S" },
      { id: "2108-m", name: "M", stock: 6, sku: "VF-2108-M" },
      { id: "2108-l", name: "L", stock: 2, sku: "VF-2108-L" },
      { id: "2108-xl", name: "XL", stock: 4, sku: "VF-2108-XL" },
      { id: "2108-xxl", name: "XXL", stock: 2, sku: "VF-2108-XXL" },
    ],
    tag: "MÁS VENDIDO",
    description:
      "La prenda insignia del Drop 01. Una camiseta oversize de estructura rígida que no pierde su forma durante el día. Hombros caídos con caída limpia que resalta la corpulencia del atleta sin verse desaliñada.",
    specifications: {
      gramaje: "280 GSM (Tejido Ultra Pesado de Élite)",
      composicion: "100% Algodón Peruano Premium Peinado",
      corte: "Boxy Oversized Caído (Drop Shoulder)",
      cuello: "Cuello cerrado reforzado de 3.5 cm (No se deforma)",
      cuidados: "Lavar a máquina en ciclo suave • No planchar directamente sobre los gráficos",
    },
    features: [
      "Insignia 'VITAL' en acabado cromo plateado y 'FIT' en rojo abrasivo al frente",
      "Radiografía anatómica esquelética completa en la espalda de altísima durabilidad",
      "Tejido preshrunk preencogido: no se reduce tras la primera lavada",
      "Corte boxy con caída angular que crea ilusión óptica de hombros más anchos",
    ],
    sizeGuide: [
      { size: "S", chest: "116 cm", length: "74 cm", shoulders: "56 cm" },
      { size: "M", chest: "122 cm", length: "76 cm", shoulders: "58 cm" },
      { size: "L", chest: "128 cm", length: "78 cm", shoulders: "60 cm" },
      { size: "XL", chest: "134 cm", length: "80 cm", shoulders: "62 cm" },
      { size: "XXL", chest: "140 cm", length: "82 cm", shoulders: "64 cm" },
    ],
    vitalFitPerk: "Incluye pase de acceso a la comunidad privada de Atletas VitalFit en la App.",
  },
  {
    id: "prod-4309",
    code: "4309",
    name: "CAMISETA MUSCULAR // PURE FIT BLANCA",
    subtitle: "Ajuste Anatómico • Algodón Elástano 240 GSM • Escote Ergonómico",
    slug: "4309-camiseta-muscular-pure-fit",
    gender: "him",
    price: 109900,
    compareAtPrice: 130000,
    currency: "COP",
    images: [
      "/products/white-muscle-tee.jpg",
      "/products/tank-esquelto.jpg",
    ],
    swatches: [
      { name: "Blanco Puro", colorCode: "#ffffff" },
      { name: "Negro Carbón", colorCode: "#1c1c1c" },
      { name: "Gris Jaspe", colorCode: "#6b6b6b" },
      { name: "Arena Desierto", colorCode: "#d8cca3" },
    ],
    variants: [
      { id: "4309-s", name: "S", stock: 4, sku: "VF-4309-S" },
      { id: "4309-m", name: "M", stock: 8, sku: "VF-4309-M" },
      { id: "4309-l", name: "L", stock: 5, sku: "VF-4309-L" },
      { id: "4309-xl", name: "XL", stock: 2, sku: "VF-4309-XL" },
      { id: "4309-xxl", name: "XXL", stock: 0, sku: "VF-4309-XXL" },
    ],
    description:
      "La camiseta de corte atlético ajustado para quienes quieren lucir el físico conseguido en el gimnasio. Ajuste ceñido en brazos y pecho con caída relajada en la zona abdominal.",
    specifications: {
      gramaje: "240 GSM con memoria elástica",
      composicion: "95% Algodón Peinado • 5% Elastano",
      corte: "Fitted Athletic (Entallado en brazos y pecho)",
      cuidados: "Lavar con colores similares • Planchar a temperatura media",
    },
    features: [
      "Mangas contorneadas que abrazan los bíceps y tríceps",
      "Parche micro-tejido tonal de VitalFit en el pecho",
      "Transpirabilidad natural de algodón orgánico",
      "Tejido flexible para sentadillas y press sin restricciones",
    ],
    sizeGuide: [
      { size: "S", chest: "98 cm", length: "70 cm", shoulders: "44 cm" },
      { size: "M", chest: "104 cm", length: "72 cm", shoulders: "46 cm" },
      { size: "L", chest: "110 cm", length: "74 cm", shoulders: "48 cm" },
      { size: "XL", chest: "116 cm", length: "76 cm", shoulders: "50 cm" },
    ],
    vitalFitPerk: "Acceso al módulo de seguimiento de medidas corporales dentro de la App VitalFit.",
  },
  {
    id: "prod-9102",
    code: "9102",
    name: "CREATINA MONOHIDRATADA PURA 200 MESH",
    subtitle: "100% Micronizada Grado Farmacéutico • 60 Servicios • 5g por Scoop",
    slug: "9102-creatina-monohidratada-pura-savage",
    gender: "supplements",
    price: 129000,
    compareAtPrice: 155000,
    currency: "COP",
    images: [
      "/products/creatina-savage.jpg",
    ],
    swatches: [
      { name: "Sin Sabor (300g)", colorCode: "#000000" },
      { name: "Ponche de Frutas", colorCode: "#b91c1c" },
    ],
    variants: [
      { id: "9102-unf", name: "300g (60 Servicios)", stock: 15, sku: "VF-9102-UNF" },
      { id: "9102-fp", name: "Fruit Punch (60 Serv)", stock: 8, sku: "VF-9102-FP" },
    ],
    tag: "100% PURA",
    description:
      "Creatina monohidratada micronizada al estándar 200 Mesh para una disolución instantánea sin grumos en agua fría. El suplemento con mayor evidencia científica en el mundo para ganancias de fuerza, síntesis proteica e hipertrofia.",
    specifications: {
      gramaje: "300 Gramos Netos (60 Servicios de 5g)",
      composicion: "100% Monohidrato de Creatina Micronizado",
      corte: "Polvo Ultra Fino 200 Mesh",
      cuidados: "Mantener en lugar fresco y seco • Cerrar bien la tapa de aluminio",
    },
    features: [
      "5.000 mg de creatina pura por servicio sin rellenos añadidos",
      "Cero carbohidratos, cero sodio añadido, sin saborizantes artificiales (versión pura)",
      "Mejora comprobada en la producción de ATP y fuerza explosiva en series pesadas",
      "Tarro negro mate con acabado premium y cuchara dosificadora de 5g incluida",
    ],
    vitalFitPerk: "Calculadora de fase de carga y saturación de creatina personalizada en la App VitalFit.",
  },
  {
    id: "prod-8810",
    code: "8810",
    name: "HOODIE HEAVYWEIGHT // ACID IRON 400 GSM",
    subtitle: "Boxy Relaxed Fit • Felpa Pesada 400 GSM • Lavado Mineral Ácido",
    slug: "8810-hoodie-heavyweight-acid-iron",
    gender: "him",
    price: 219900,
    compareAtPrice: 260000,
    currency: "COP",
    images: [
      "/products/hoodie-acid.jpg",
      "/products/oversize-metal.jpg",
    ],
    swatches: [
      { name: "Gris Carbón Ácido", colorCode: "#2a2a2b" },
      { name: "Negro Lavado", colorCode: "#171718" },
    ],
    variants: [
      { id: "8810-s", name: "S", stock: 2, sku: "VF-8810-S" },
      { id: "8810-m", name: "M", stock: 3, sku: "VF-8810-M" },
      { id: "8810-l", name: "L", stock: 1, sku: "VF-8810-L" },
      { id: "8810-xl", name: "XL", stock: 2, sku: "VF-8810-XL" },
      { id: "8810-xxl", name: "XXL", stock: 1, sku: "VF-8810-XXL" },
    ],
    tag: "DROP EXCLUSIVO",
    description:
      "El buzo definitivo para calentar pesado o vestir en la calle. Confeccionado con 400 gramos de felpa de algodón denso y capucha estructurada de doble capa sin cordones para una caída limpia e imponente.",
    specifications: {
      gramaje: "400 GSM (Felpa Ultra Pesada de Invierno)",
      composicion: "100% Algodón Peinado sin mezcla sintética",
      corte: "Boxy Drop Shoulder Oversized",
      cuello: "Capucha doble capa sin cordones colgantes",
      cuidados: "Lavar a mano o ciclo suave en frío • Secar extendido en plano",
    },
    features: [
      "Letras tonales 'VITALFIT' grabadas en bajo relieve en el pecho",
      "Bolsillo canguro frontal reforzado con costuras ocultas",
      "Puños acanalados elásticos de 2x2 que no se vencen al subirlos a los antebrazos",
      "Tratamiento artesanal de teñido ácido mineral en Medellín",
    ],
    sizeGuide: [
      { size: "S", chest: "118 cm", length: "72 cm", shoulders: "58 cm" },
      { size: "M", chest: "124 cm", length: "74 cm", shoulders: "60 cm" },
      { size: "L", chest: "130 cm", length: "76 cm", shoulders: "62 cm" },
      { size: "XL", chest: "136 cm", length: "78 cm", shoulders: "64 cm" },
      { size: "XXL", chest: "142 cm", length: "80 cm", shoulders: "66 cm" },
    ],
    vitalFitPerk: "Acceso a la 'Guía de Calentamiento y Movilidad Articular para Cargas Pesadas' en la App.",
  },
  {
    id: "prod-7721",
    code: "7721",
    name: "PRE-ENTRENO // BLOOD RUSH 400MG",
    subtitle: "8g Citrulina Malato • 400mg Cafeína Anhidra • 3.2g Beta-Alanina",
    slug: "7721-pre-entreno-blood-rush-400mg",
    gender: "supplements",
    price: 149900,
    compareAtPrice: 175000,
    currency: "COP",
    images: [
      "/products/preentreno-bloodrush.jpg",
    ],
    swatches: [
      { name: "Fruit Punch Savage", colorCode: "#b91c1c" },
      { name: "Sour Blue Razz", colorCode: "#2563eb" },
    ],
    variants: [
      { id: "7721-fp", name: "Punch (30 Serv)", stock: 4, sku: "VF-7721-FP" },
      { id: "7721-sbr", name: "Blue Razz (30 Serv)", stock: 2, sku: "VF-7721-SBR" },
    ],
    tag: "ALTA ESTIMULACIÓN",
    description:
      "Fórmula de congestión muscular extrema y enfoque láser sin bajón. Diseñado para sesiones de piernas pesadas y récord personal de levantamiento.",
    specifications: {
      gramaje: "300g Netos (30 Scoops de Máxima Potencia)",
      composicion: "Citrulina 2:1, Beta Alanina, Tirosina, Cafeína Pura y Sal Rosada",
      corte: "Polvo Soluble Instantáneo",
      cuidados: "Tomar 20 minutos antes de entrenar con agua fría • No tomar de noche",
    },
    features: [
      "Vasodilatación masiva y bombeo vascular por horas",
      "Cero azúcar añadido, saborizado naturalmente",
      "Enfoque neurosensorial sostenido sin taquicardia descontrolada",
    ],
    vitalFitPerk: "Timer de sincronización pre-entreno y seguimiento de frecuencia cardíaca en la App.",
  },
  {
    id: "prod-3342",
    code: "3342",
    name: "SHORT DE ENTRENAMIENTO // RAW CUT 5-INCH",
    subtitle: "Tiro 5 Pulgadas • Algodón Francés Pesado • Dobladillo Deshilachado",
    slug: "3342-short-entrenamiento-raw-cut-5inch",
    gender: "him",
    price: 99900,
    compareAtPrice: 125000,
    currency: "COP",
    images: [
      "/products/short-lifter.jpg",
      "/products/tank-esquelto.jpg",
    ],
    swatches: [
      { name: "Negro Mineral Lavado", colorCode: "#242426" },
      { name: "Gris Cemento", colorCode: "#606066" },
    ],
    variants: [
      { id: "3342-s", name: "S", stock: 3, sku: "VF-3342-S" },
      { id: "3342-m", name: "M", stock: 5, sku: "VF-3342-M" },
      { id: "3342-l", name: "L", stock: 2, sku: "VF-3342-L" },
      { id: "3342-xl", name: "XL", stock: 3, sku: "VF-3342-XL" },
    ],
    tag: "CORTE 5 PULGADAS",
    description:
      "El short que deja ver el cuádriceps completo durante la sentadilla. Corte clásico de culturismo de los años 90 con dobladillo inferior al corte vivo y bolsillo profundo con cremallera invisible.",
    specifications: {
      gramaje: "320 GSM French Terry",
      composicion: "100% Algodón Rústico Peinado",
      corte: "Inseam de 5 Pulgadas por encima de la rodilla",
      cuidados: "Lavar al revés • No retorcer",
    },
    features: [
      "Bolsillo lateral oculto con cremallera YKK para celular",
      "Cordones gruesos de algodón con herrajes de acero inoxidable grabado",
      "Bordado tonal 'VITALFIT' en la pierna izquierda",
    ],
    sizeGuide: [
      { size: "S", chest: "Cintura: 74-80 cm", length: "Largo: 36 cm", shoulders: "Tiro: 5 in" },
      { size: "M", chest: "Cintura: 80-86 cm", length: "Largo: 38 cm", shoulders: "Tiro: 5 in" },
      { size: "L", chest: "Cintura: 86-92 cm", length: "Largo: 40 cm", shoulders: "Tiro: 5 in" },
      { size: "XL", chest: "Cintura: 92-98 cm", length: "Largo: 42 cm", shoulders: "Tiro: 5 in" },
    ],
    vitalFitPerk: "Módulo de hipertrofia de cuádriceps y femorales 'Leg Day Savage' en la App.",
  },
  {
    id: "prod-6655",
    code: "6655",
    name: "PROTEÍNA AISLADA // CFM WHEY ISOLATE 100% PURA",
    subtitle: "25g Proteína por Scoop • Filtración CFM en Frío • Cero Lactosa",
    slug: "6655-proteina-aislada-cfm-whey-isolate",
    gender: "supplements",
    price: 189900,
    compareAtPrice: 220000,
    currency: "COP",
    images: [
      "/products/whey-isolate.jpg",
    ],
    swatches: [
      { name: "Chocolate Suizo", colorCode: "#3b1e08" },
      { name: "Vainilla Natural", colorCode: "#f5edd6" },
    ],
    variants: [
      { id: "6655-choc", name: "Chocolate (2 Lbs)", stock: 3, sku: "VF-6655-CHOC" },
      { id: "6655-van", name: "Vainilla (2 Lbs)", stock: 2, sku: "VF-6655-VAN" },
    ],
    tag: "25G PROTEÍNA PURA",
    description:
      "Aislado de suero de leche obtenido por microfiltración de flujo cruzado (CFM) a baja temperatura para preservar todas las fracciones bioactivas. Digestión ultrarrápida sin pesadez ni inflamación.",
    specifications: {
      gramaje: "908g Netos (30 Servicios de 30g)",
      composicion: "100% CFM Whey Protein Isolate",
      corte: "Ultra Instantánea en Agua Fría",
      cuidados: "Guardar en lugar fresco y seco",
    },
    features: [
      "25g de proteína pura y 5.8g de BCAAs naturales por servicio",
      "Menos de 1g de carbohidratos y 0g de azúcar añadido",
      "Enzimas digestivas DigeZyme para máxima absorción",
    ],
    vitalFitPerk: "Calculadora de síntesis proteica diaria ajustada a tu peso en la App.",
  },
  {
    id: "prod-2201",
    code: "2201",
    name: "CAMISETA OVERSIZE // PUMP COVER BLACKOUT",
    subtitle: "Silueta Cuadrada Boxy • Algodón 280 GSM • Serigrafía Tonal Táctil",
    slug: "2201-camiseta-oversize-pump-cover-blackout",
    gender: "him",
    price: 134900,
    compareAtPrice: 160000,
    currency: "COP",
    images: [
      "/products/oversize-metal.jpg",
      "/products/tank-esquelto.jpg",
    ],
    swatches: [
      { name: "Total Blackout", colorCode: "#0f0f10" },
      { name: "Gris Plomo", colorCode: "#424245" },
    ],
    variants: [
      { id: "2201-s", name: "S", stock: 2, sku: "VF-2201-S" },
      { id: "2201-m", name: "M", stock: 4, sku: "VF-2201-M" },
      { id: "2201-l", name: "L", stock: 1, sku: "VF-2201-L" },
      { id: "2201-xl", name: "XL", stock: 2, sku: "VF-2201-XL" },
      { id: "2201-xxl", name: "XXL", stock: 0, sku: "VF-2201-XXL" },
    ],
    tag: "MÁS PEDIDO",
    description:
      "La camiseta perfecta para llegar al gimnasio, calentar con los músculos fríos y quitarte cuando estés listo para el bombeo máximo. Cuello grueso acanalado de 3.5 cm que mantiene su forma lavado tras lavado.",
    specifications: {
      gramaje: "280 GSM Peinado",
      composicion: "100% Algodón Premium",
      corte: "Boxy Pump Cover",
      cuidados: "Lavar con agua fría • Secar a la sombra",
    },
    features: [
      "Estampado en alta densidad negro sobre negro que brilla sutilmente bajo las luces del gym",
      "Caída pesada en hombros caídos",
    ],
    sizeGuide: [
      { size: "S", chest: "116 cm", length: "74 cm", shoulders: "56 cm" },
      { size: "M", chest: "122 cm", length: "76 cm", shoulders: "58 cm" },
      { size: "L", chest: "128 cm", length: "78 cm", shoulders: "60 cm" },
      { size: "XL", chest: "134 cm", length: "80 cm", shoulders: "62 cm" },
    ],
    vitalFitPerk: "Acceso al módulo de técnica en press banca y sobrecarga progresiva en la App.",
  },
  {
    id: "prod-1190",
    code: "1190",
    name: "ESQUELETO STRINGER // OLYMPIA CLASSIC CUT",
    subtitle: "Espalda Y-Back • Algodón 260 GSM • Apertura Amplia para Dorsales",
    slug: "1190-esqueleto-stringer-olympia-classic",
    gender: "him",
    price: 114900,
    compareAtPrice: 135000,
    currency: "COP",
    images: [
      "/products/tank-esquelto.jpg",
      "/products/white-muscle-tee.jpg",
    ],
    swatches: [
      { name: "Verde Militar Vintage", colorCode: "#3a4235" },
      { name: "Negro Carbón", colorCode: "#1a1a1c" },
    ],
    variants: [
      { id: "1190-s", name: "S", stock: 3, sku: "VF-1190-S" },
      { id: "1190-m", name: "M", stock: 3, sku: "VF-1190-M" },
      { id: "1190-l", name: "L", stock: 1, sku: "VF-1190-L" },
      { id: "1190-xl", name: "XL", stock: 2, sku: "VF-1190-XL" },
    ],
    tag: "CORTE GOLDEN ERA",
    description:
      "Inspirado en la era dorada de Venice Beach. Los tirantes delgados y el escote profundo en la espalda permiten ver el movimiento de los omóplatos y la activación del dorsal en cada jalón.",
    specifications: {
      gramaje: "260 GSM Acanalado",
      composicion: "100% Algodón Peinado Elástico",
      corte: "Stringer Y-Back Profundo",
      cuidados: "Lavar con agua fría • No usar secadora caliente",
    },
    features: [
      "Costuras elásticas en las sisas que previenen rozaduras en el sobaco",
      "Serigrafía gastada estilo vintage en el pecho",
    ],
    sizeGuide: [
      { size: "S", chest: "104 cm", length: "72 cm", shoulders: "Stringer" },
      { size: "M", chest: "110 cm", length: "74 cm", shoulders: "Stringer" },
      { size: "L", chest: "116 cm", length: "76 cm", shoulders: "Stringer" },
      { size: "XL", chest: "122 cm", length: "78 cm", shoulders: "Stringer" },
    ],
    vitalFitPerk: "Rutina especializada de dorsales y trapecios 'V-Taper Anatomy' en la App.",
  },
  {
    id: "prod-5511",
    code: "5511",
    name: "PANTALÓN JOGGER // HEAVY FLEECE CARGO 380 GSM",
    subtitle: "Corte Tapered Ajustado en Tobillo • Felpa 380 GSM • Bolsillos Cargo Tácticos",
    slug: "5511-pantalon-jogger-heavy-fleece-cargo",
    gender: "him",
    price: 169900,
    compareAtPrice: 210000,
    currency: "COP",
    images: [
      "/products/short-lifter.jpg",
      "/products/hoodie-acid.jpg",
    ],
    swatches: [
      { name: "Negro Lavado", colorCode: "#171718" },
      { name: "Gris Cemento", colorCode: "#525257" },
    ],
    variants: [
      { id: "5511-s", name: "S", stock: 3, sku: "VF-5511-S" },
      { id: "5511-m", name: "M", stock: 4, sku: "VF-5511-M" },
      { id: "5511-l", name: "L", stock: 2, sku: "VF-5511-L" },
      { id: "5511-xl", name: "XL", stock: 1, sku: "VF-5511-XL" },
    ],
    tag: "380 GSM PESADO",
    description:
      "Diseñado para soportar el frío y mantener las articulaciones de las rodillas calientes durante las series pesadas. Confeccionado en felpa densa de 380 GSM con bolsillos tácticos cargo y elástico grueso en el tobillo.",
    specifications: {
      gramaje: "380 GSM French Terry Pesado",
      composicion: "100% Algodón Peinado sin pelusa",
      corte: "Relaxed Tapered (Holgado en muslos, ajustado en pantorrillas)",
      cuidados: "Lavar al revés con agua fría",
    },
    features: [
      "Bolsillos cargo laterales con broches metálicos a presión",
      "Pretina ancha con cordón interno reforzado para que no se caiga al agacharse",
      "Tiro cómodo diseñado para no restringir la flexión profunda de cadera",
    ],
    sizeGuide: [
      { size: "S", chest: "Cintura: 74-80 cm", length: "Largo: 100 cm", shoulders: "Tobillo: 12 cm" },
      { size: "M", chest: "Cintura: 80-86 cm", length: "Largo: 102 cm", shoulders: "Tobillo: 13 cm" },
      { size: "L", chest: "Cintura: 86-92 cm", length: "Largo: 104 cm", shoulders: "Tobillo: 14 cm" },
      { size: "XL", chest: "Cintura: 92-98 cm", length: "Largo: 106 cm", shoulders: "Tobillo: 15 cm" },
    ],
    vitalFitPerk: "Acceso al módulo 'Rodillas de Acero: Calentamiento de Sentadilla' en la App.",
  },
  {
    id: "prod-9922",
    code: "9922",
    name: "CINTURÓN DE FUERZA // LEVER BELT 10MM ACERO INOXIDABLE",
    subtitle: "10mm Espesor Powerlifting • Cuero Genuino 100% • Palanca de Acero Endurecido",
    slug: "9922-cinturon-de-fuerza-lever-belt-10mm",
    gender: "him",
    price: 249900,
    compareAtPrice: 290000,
    currency: "COP",
    images: [
      "/products/oversize-metal.jpg",
      "/products/tank-esquelto.jpg",
    ],
    swatches: [
      { name: "Negro Mate / Palanca Cromo", colorCode: "#111111" },
    ],
    variants: [
      { id: "9922-s", name: "S (65-75 cm)", stock: 2, sku: "VF-9922-S" },
      { id: "9922-m", name: "M (75-85 cm)", stock: 3, sku: "VF-9922-M" },
      { id: "9922-l", name: "L (85-95 cm)", stock: 2, sku: "VF-9922-L" },
      { id: "9922-xl", name: "XL (95-105 cm)", stock: 1, sku: "VF-9922-XL" },
    ],
    tag: "CUERO 10MM",
    description:
      "El cinturón que necesitas para romper tu récord personal en sentadilla y peso muerto. Construido con 10mm de cuero genuino indeformable y una palanca de acero endurecido que se cierra con un solo golpe seco.",
    specifications: {
      gramaje: "10mm de Grosor Estándar IPF",
      composicion: "Cuero Genuino Rígido con Forro Interior de Gamuza Negra",
      corte: "Ancho Uniforme de 4 Pulgadas (10 cm)",
      cuidados: "Limpiar con paño seco • No exponer a humedad extrema",
    },
    features: [
      "Palanca de cierre rápido en acero grabado con láser 'VITALFIT'",
      "Gamuza antideslizante interior para evitar giros en el torso",
      "Costuras cuádruples de alta resistencia a la tracción",
    ],
    sizeGuide: [
      { size: "S", chest: "Cintura: 65-75 cm", length: "Ancho: 10 cm", shoulders: "Grosor: 10 mm" },
      { size: "M", chest: "Cintura: 75-85 cm", length: "Ancho: 10 cm", shoulders: "Grosor: 10 mm" },
      { size: "L", chest: "Cintura: 85-95 cm", length: "Ancho: 10 cm", shoulders: "Grosor: 10 mm" },
      { size: "XL", chest: "Cintura: 95-105 cm", length: "Ancho: 10 cm", shoulders: "Grosor: 10 mm" },
    ],
    vitalFitPerk: "Calculadora de maniobra Valsalva y presión intraabdominal en la App.",
  },
  {
    id: "prod-4433",
    code: "4433",
    name: "STRAPS DE LEVANTAMIENTO // HEAVY LEATHER DEADLIFT",
    subtitle: "100% Cuero Vacuno Colombiano • Costuras Kevlar • Soporte para +250 KG",
    slug: "4433-straps-levantamiento-heavy-leather",
    gender: "him",
    price: 64900,
    compareAtPrice: 80000,
    currency: "COP",
    images: [
      "/products/tank-esquelto.jpg",
      "/products/white-muscle-tee.jpg",
    ],
    swatches: [
      { name: "Cuero Negro Grano Entero", colorCode: "#1c1c1c" },
    ],
    variants: [
      { id: "4433-u", name: "Talla Única (Par)", stock: 8, sku: "VF-4433-PAIR" },
    ],
    tag: "CUERO GENUINO",
    description:
      "Olvídate de que el agarre te limite en el peso muerto y los remos con barra pesados. El cuero natural se amolda a tu mano con el sudor y crea una tracción superior a cualquier correa sintética.",
    specifications: {
      gramaje: "Cuero de 3.5mm de Espesor",
      composicion: "100% Cuero Bovino de Exportación",
      corte: "Largo de 58 cm x Ancho de 4 cm",
      cuidados: "Dejar secar al aire tras entrenar",
    },
    features: [
      "Extremo biselado para enrollar fácilmente con una sola mano alrededor de la barra",
      "Estampado en bajorrelieve 'VITALFIT LIFTER' en ambas correas",
    ],
    vitalFitPerk: "Guía de biomecánica de tracción y agarre para espalda en la App.",
  },
  {
    id: "prod-8844",
    code: "8844",
    name: "ELECTROLITOS & HIDRATACIÓN // HYDRA-SHIELD MATRIX",
    subtitle: "Sodio del Himalaya • Citrato de Potasio • Magnesio Quelado • 60 Servicios",
    slug: "8844-electrolitos-hidratacion-hydra-shield",
    gender: "supplements",
    price: 89900,
    compareAtPrice: 115000,
    currency: "COP",
    images: [
      "/products/preentreno-bloodrush.jpg",
      "/products/creatina-savage.jpg",
    ],
    swatches: [
      { name: "Lima Limón Savage", colorCode: "#84cc16" },
      { name: "Mora Azul Glaciar", colorCode: "#3b82f6" },
    ],
    variants: [
      { id: "8844-lim", name: "Lima Limón (60 Serv)", stock: 6, sku: "VF-8844-LIM" },
      { id: "8844-mor", name: "Mora Azul (60 Serv)", stock: 4, sku: "VF-8844-MOR" },
    ],
    tag: "CERO CALAMBRES",
    description:
      "Durante entrenamientos pesados de más de 60 minutos en climas cálidos de Colombia, la pérdida de sodio reduce tu fuerza en hasta un 15%. Hydra-Shield restaura el balance osmótico para bombeos plenos.",
    specifications: {
      gramaje: "360g Netos (60 Servicios de 6g)",
      composicion: "Sodio 500mg, Potasio 200mg, Magnesio 60mg, Calcio y Agua de Coco en Polvo",
      corte: "Disolución Instantánea",
      cuidados: "Consumir intra-entreno mezclado con 700ml de agua fría",
    },
    features: [
      "Sin azúcar añadida, apto para etapas de definición y cetosis",
      "Previene contracturas musculares y fatiga del sistema nervioso",
    ],
    vitalFitPerk: "Calculadora de tasa de sudoración y rehidratación por sesión en la App.",
  },
  {
    id: "prod-1020",
    code: "1020",
    name: "TOP DEPORTIVO // HIGH SUPPORT CROSS-BACK",
    subtitle: "Espalda Cruzada Anatómica • Soporte Firme • Tejido Transpirable Soft-Touch",
    slug: "1020-top-deportivo-high-support-crossback",
    gender: "her",
    price: 89900,
    compareAtPrice: 110000,
    currency: "COP",
    images: [
      "/products/white-muscle-tee.jpg",
      "/products/oversize-metal.jpg",
    ],
    swatches: [
      { name: "Negro Ónix", colorCode: "#141414" },
      { name: "Blanco Perla", colorCode: "#fafafa" },
    ],
    variants: [
      { id: "1020-xs", name: "XS", stock: 3, sku: "VF-1020-XS" },
      { id: "1020-s", name: "S", stock: 4, sku: "VF-1020-S" },
      { id: "1020-m", name: "M", stock: 3, sku: "VF-1020-M" },
      { id: "1020-l", name: "L", stock: 2, sku: "VF-1020-L" },
    ],
    tag: "ALTO SOPORTE",
    description:
      "Diseñado para atletas femeninas que entrenan pesado. Banda elástica inferior ancha que permanece en su lugar durante saltos, sentadillas y empujes sin pellizcar la piel.",
    specifications: {
      gramaje: "290 GSM Nylon / Spandex Micro-Ribbed",
      composicion: "80% Poliamida Soft • 20% Elastano",
      corte: "Medium-High Impact Support con Copas Removibles",
      cuidados: "Lavar con agua fría en bolsa de prendas delicadas",
    },
    features: [
      "Tirantes dobles cruzados que distribuyen el peso sin sobrecargar los trapecios",
      "Tejido con compresión de contorno y secado rápido anti-sudor",
    ],
    sizeGuide: [
      { size: "XS", chest: "Contorno: 78-83 cm", length: "Copa: 30A-32B", shoulders: "Banda: 64 cm" },
      { size: "S", chest: "Contorno: 84-89 cm", length: "Copa: 32B-34B", shoulders: "Banda: 68 cm" },
      { size: "M", chest: "Contorno: 90-95 cm", length: "Copa: 34C-36B", shoulders: "Banda: 72 cm" },
      { size: "L", chest: "Contorno: 96-102 cm", length: "Copa: 36C-38C", shoulders: "Banda: 76 cm" },
    ],
    vitalFitPerk: "Acceso al módulo de hipertrofia femenina 'Glute & Upper Fit' en la App.",
  },
  {
    id: "prod-1030",
    code: "1030",
    name: "BIKER SHORTS // SCULPT SEAMLESS HIGH WAIST",
    subtitle: "Tiro Alto Moldeador • Squat-Proof 100% Sin Transparencias • Longitud 6 Pulgadas",
    slug: "1030-biker-shorts-sculpt-seamless-high-waist",
    gender: "her",
    price: 99900,
    compareAtPrice: 125000,
    currency: "COP",
    images: [
      "/products/short-lifter.jpg",
      "/products/white-muscle-tee.jpg",
    ],
    swatches: [
      { name: "Negro Azabache", colorCode: "#171718" },
      { name: "Gris Grafito", colorCode: "#4a4a50" },
    ],
    variants: [
      { id: "1030-xs", name: "XS", stock: 2, sku: "VF-1030-XS" },
      { id: "1030-s", name: "S", stock: 5, sku: "VF-1030-S" },
      { id: "1030-m", name: "M", stock: 4, sku: "VF-1030-M" },
      { id: "1030-l", name: "L", stock: 2, sku: "VF-1030-L" },
    ],
    tag: "SQUAT-PROOF",
    description:
      "Totalmente a prueba de sentadillas: cero transparencias incluso bajo las luces más potentes del gimnasio. Pretina alta compresiva con soporte de cintura que no se enrolla durante el entrenamiento.",
    specifications: {
      gramaje: "310 GSM Seamless Knit Ultra Denso",
      composicion: "88% Nylon • 12% Spandex",
      corte: "High Waist Biker de 6 Pulgadas",
      cuidados: "Lavar al revés • No planchar",
    },
    features: [
      "Estructura anatómica que realza los glúteos de forma sutil y natural",
      "Costura reforzada en entrepierna en forma de rombo para máxima elasticidad",
    ],
    sizeGuide: [
      { size: "XS", chest: "Cintura: 58-64 cm", length: "Cadera: 84-90 cm", shoulders: "Inseam: 6 in" },
      { size: "S", chest: "Cintura: 64-70 cm", length: "Cadera: 90-96 cm", shoulders: "Inseam: 6 in" },
      { size: "M", chest: "Cintura: 70-76 cm", length: "Cadera: 96-102 cm", shoulders: "Inseam: 6 in" },
      { size: "L", chest: "Cintura: 76-82 cm", length: "Cadera: 102-108 cm", shoulders: "Inseam: 6 in" },
    ],
    vitalFitPerk: "Rutina especializada de tren inferior 'Glute Overload' en la App.",
  },
];


